# Generated by Django 5.2.13 on 2026-09-18 16:26

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import lumina.core.models
import lumina.core.review
import lumina.hardware.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Component",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("model_number", models.CharField(blank=True, max_length=120)),
                ("description", models.TextField(blank=True)),
                (
                    "vendor_spec_url",
                    models.URLField(
                        blank=True,
                        help_text="Link to the vendor's spec sheet for this listing. Surfaced as a CTA on the public detail page.",
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                ("published", models.BooleanField(default=False)),
                (
                    "validation_level",
                    models.CharField(
                        choices=[
                            ("community", "Community-validated"),
                            ("vendor", "Vendor-validated"),
                            ("almalinux", "AlmaLinux-validated"),
                        ],
                        default="community",
                        max_length=16,
                    ),
                ),
                ("attestation_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("cpu", "CPU"),
                            ("motherboard", "Motherboard"),
                            ("gpu", "GPU"),
                            ("nic", "NIC"),
                            ("storage", "Storage"),
                            ("management", "Management"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        default="other",
                        max_length=16,
                    ),
                ),
                ("attributes", models.JSONField(blank=True, default=dict)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("model", "Specific model"),
                            ("family", "Family / generation"),
                        ],
                        db_index=True,
                        default="model",
                        help_text="A specific model is one part as the hardware reports it. A family covers a generation and owns the matching patterns below.",
                        max_length=8,
                    ),
                ),
                (
                    "model_patterns",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="One regular expression per line, matched case-insensitively against reported model strings. Leave empty for a specific model rather than a family. Keep a family to a single generation and socket: certifying one member certifies every model the patterns match, so a pattern spanning sockets (e.g. all “Xeon E” generations, which change socket across E-2100/2200/2300/2400) would certify hardware the run never ran on. Prefer per-generation families like “Xeon E-2300 Series”.",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "abstract": False,
            },
            bases=(lumina.core.models.VendorSlugMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ComponentExclusionRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vendor_id",
                    models.CharField(
                        blank=True,
                        help_text="PCI vendor id, 4 hex digits (e.g. 1a03). Blank matches any vendor.",
                        max_length=4,
                    ),
                ),
                (
                    "device_id",
                    models.CharField(
                        blank=True,
                        help_text="PCI device id, 4 hex digits (e.g. 164e). Blank matches any device of the vendor.",
                        max_length=4,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("cpu", "CPU"),
                            ("motherboard", "Motherboard"),
                            ("gpu", "GPU"),
                            ("nic", "NIC"),
                            ("storage", "Storage"),
                            ("management", "Management"),
                            ("other", "Other"),
                        ],
                        help_text="Restrict to one component kind. Blank matches any.",
                        max_length=16,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        help_text="Shown beside the excluded device on the review screen, e.g. 'onboard iGPU, not the accelerator under test'.",
                        max_length=200,
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["vendor_id", "device_id"],
            },
        ),
        migrations.CreateModel(
            name="ComponentNamingRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("cpu", "CPU"),
                            ("motherboard", "Motherboard"),
                            ("gpu", "GPU"),
                            ("nic", "NIC"),
                            ("storage", "Storage"),
                            ("management", "Management"),
                            ("other", "Other"),
                        ],
                        help_text="Restrict to one component kind. Blank matches any.",
                        max_length=16,
                    ),
                ),
                (
                    "match_field",
                    models.CharField(
                        blank=True,
                        help_text="Which field the pattern below runs against. Blank means the part's own model. Any path a template can read, e.g. cpu.model.",
                        max_length=200,
                    ),
                ),
                (
                    "model_pattern",
                    models.CharField(
                        blank=True,
                        help_text="Regular expression the field above must match, case-insensitive (e.g. ^Altra). Its captures are what the template reads as match.1, match.2, which is why this is a field of its own rather than a condition.",
                        max_length=200,
                    ),
                ),
                (
                    "conditions",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Everything else the part must satisfy, all of it: [{"field": "pci.vendor_id", "op": "eq", "value": "8086"}]. Any field the template can read can be tested, with any operator, which is why vendor and the PCI ids are not fields here: they were three of the available hundreds, and being fields made them look like the only three.',
                    ),
                ),
                (
                    "build",
                    models.TextField(
                        help_text="Jinja template for the name, e.g. {{ dmi.processor[0]['Part Number'] }}."
                    ),
                ),
                (
                    "fallback",
                    models.TextField(
                        blank=True,
                        help_text="Used when the template above renders empty - the machine did not report the field it needs. Compose something that still distinguishes the part, e.g. {{ model }} ({{ cpu.cores }}-core).",
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=100,
                        help_text="Lowest first. Leave room between rules (10, 20, 30) so one can be inserted between two later without renumbering.",
                    ),
                ),
                (
                    "built_in",
                    models.BooleanField(
                        default=False,
                        help_text="Shipped with lumina, reproducing behaviour that used to be in code. Editable, but a change here changes how every machine of that shape is named.",
                    ),
                ),
                (
                    "notes",
                    models.CharField(
                        blank=True,
                        help_text="Why this rule exists, for whoever reads it next.",
                        max_length=300,
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["priority", "id"],
            },
        ),
        migrations.CreateModel(
            name="ListingCategoryValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ListingEditProposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=200)),
                ("model_number", models.CharField(blank=True, max_length=120)),
                ("description", models.TextField(blank=True)),
                ("vendor_spec_url", models.URLField(blank=True)),
                ("submitter_notes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("needs-changes", "Needs changes"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("reviewer_notes", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-submitted_at"],
            },
            bases=(lumina.core.review.ReviewWorkflow, models.Model),
        ),
        migrations.CreateModel(
            name="ListingVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("run", "Proven by a validation run"),
                            ("declared", "Declared, not yet validated"),
                        ],
                        default="declared",
                        help_text="Rows created by an approved validation run are marked as proven. Anything added by hand is a declaration until a run confirms it.",
                        max_length=10,
                    ),
                ),
                (
                    "available_from_minor",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="The minor of this major in which the hardware enablement lands, when the evidence came from AlmaLinux Kitten. The listing is published and carries a disclaimer naming this minor until ``AlmaLinuxRelease.latest_minor`` reaches it. Null means the claim is live.",
                        null=True,
                    ),
                ),
                (
                    "validation_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("community", "Community-validated"),
                            ("vendor", "Vendor-validated"),
                            ("almalinux", "AlmaLinux-validated"),
                        ],
                        db_index=True,
                        default="",
                        help_text="Highest tier among this release's attestations. Empty while the row is only declared.",
                        max_length=16,
                    ),
                ),
            ],
            options={
                "ordering": ["-release__major"],
            },
        ),
        migrations.CreateModel(
            name="NameSuggestionField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("cpu", "CPU"),
                            ("motherboard", "Motherboard"),
                            ("gpu", "GPU"),
                            ("nic", "NIC"),
                            ("storage", "Storage"),
                            ("management", "Management"),
                            ("other", "Other"),
                        ],
                        help_text="The component kind this field is offered for.",
                        max_length=16,
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        help_text="Where the value is, in the same paths a naming rule reads. Use * for a list index: dmi.processor.*.Part Number",
                        max_length=200,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text='What to call it when it is offered, e.g. "Processor part number". Shown under the value, so it only has to tell two similar values apart.',
                        max_length=80,
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=100,
                        help_text="Lowest first, which is the order they are offered in.",
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                (
                    "built_in",
                    models.BooleanField(
                        default=False,
                        help_text="Shipped with lumina. Editable, like any other row.",
                    ),
                ),
            ],
            options={
                "ordering": ["kind", "priority", "id"],
            },
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "claimed_validation_level",
                    models.CharField(
                        choices=[
                            ("community", "Community-validated"),
                            ("vendor", "Vendor-validated"),
                            ("almalinux", "AlmaLinux-validated"),
                        ],
                        default="community",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("needs-changes", "Needs changes"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("reviewer_notes", models.TextField(blank=True)),
                ("submitter_notes", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-submitted_at"],
            },
            bases=(lumina.core.review.ReviewWorkflow, models.Model),
        ),
        migrations.CreateModel(
            name="System",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("model_number", models.CharField(blank=True, max_length=120)),
                ("description", models.TextField(blank=True)),
                (
                    "vendor_spec_url",
                    models.URLField(
                        blank=True,
                        help_text="Link to the vendor's spec sheet for this listing. Surfaced as a CTA on the public detail page.",
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                ("published", models.BooleanField(default=False)),
                (
                    "validation_level",
                    models.CharField(
                        choices=[
                            ("community", "Community-validated"),
                            ("vendor", "Vendor-validated"),
                            ("almalinux", "AlmaLinux-validated"),
                        ],
                        default="community",
                        max_length=16,
                    ),
                ),
                ("attestation_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
                "abstract": False,
            },
            bases=(lumina.core.models.VendorSlugMixin, models.Model),
        ),
        migrations.CreateModel(
            name="TestResultAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=lumina.hardware.models._test_result_upload_to
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=300)),
                ("sha256", models.CharField(blank=True, max_length=64)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="CommunityAttestation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("community", "Community-validated"),
                            ("vendor", "Vendor-validated"),
                            ("almalinux", "AlmaLinux-validated"),
                        ],
                        default="community",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "attested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hardware_attestations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
