# Generated by Django 5.2.13 on 2026-08-04 18:55

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import lumina.hardware.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Component",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("model_number", models.CharField(blank=True, max_length=120)),
                ("description", models.TextField(blank=True)),
                (
                    "vendor_spec_url",
                    models.URLField(
                        blank=True,
                        help_text="Link to the vendor's spec sheet for this listing. Surfaced as a CTA on the public detail page.",
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                ("published", models.BooleanField(default=False)),
                (
                    "validation_level",
                    models.CharField(
                        choices=[
                            ("community", "Community-validated"),
                            ("vendor", "Vendor-validated"),
                            ("almalinux", "AlmaLinux-validated"),
                        ],
                        default="community",
                        max_length=16,
                    ),
                ),
                ("attestation_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("cpu", "CPU"),
                            ("motherboard", "Motherboard"),
                            ("gpu", "GPU"),
                            ("nic", "NIC"),
                            ("storage", "Storage"),
                            ("management", "Management"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        default="other",
                        max_length=16,
                    ),
                ),
                ("attributes", models.JSONField(blank=True, default=dict)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("model", "Specific model"),
                            ("family", "Family / generation"),
                        ],
                        db_index=True,
                        default="model",
                        help_text="A specific model is one part as the hardware reports it. A family covers a generation and owns the matching patterns below.",
                        max_length=8,
                    ),
                ),
                (
                    "model_patterns",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="One regular expression per line, matched case-insensitively against reported model strings. Leave empty for a specific model rather than a family.",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ListingCategoryValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ListingEditProposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=200)),
                ("model_number", models.CharField(blank=True, max_length=120)),
                ("description", models.TextField(blank=True)),
                ("vendor_spec_url", models.URLField(blank=True)),
                ("submitter_notes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("needs-changes", "Needs changes"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("reviewer_notes", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="ListingVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("run", "Proven by a validation run"),
                            ("declared", "Declared, not yet validated"),
                        ],
                        default="declared",
                        help_text="Rows created by an approved validation run are marked as proven. Anything added by hand is a declaration until a run confirms it.",
                        max_length=10,
                    ),
                ),
                (
                    "minimum_minor",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Minimum minor release within this major (0 = no floor).",
                    ),
                ),
                (
                    "validation_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("community", "Community-validated"),
                            ("vendor", "Vendor-validated"),
                            ("almalinux", "AlmaLinux-validated"),
                        ],
                        db_index=True,
                        default="",
                        help_text="Highest tier among this release's attestations. Empty while the row is only declared.",
                        max_length=16,
                    ),
                ),
            ],
            options={
                "ordering": ["-release__major", "minimum_minor"],
            },
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "claimed_validation_level",
                    models.CharField(
                        choices=[
                            ("community", "Community-validated"),
                            ("vendor", "Vendor-validated"),
                            ("almalinux", "AlmaLinux-validated"),
                        ],
                        default="community",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("needs-changes", "Needs changes"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("reviewer_notes", models.TextField(blank=True)),
                ("submitter_notes", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="System",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("model_number", models.CharField(blank=True, max_length=120)),
                ("description", models.TextField(blank=True)),
                (
                    "vendor_spec_url",
                    models.URLField(
                        blank=True,
                        help_text="Link to the vendor's spec sheet for this listing. Surfaced as a CTA on the public detail page.",
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                ("published", models.BooleanField(default=False)),
                (
                    "validation_level",
                    models.CharField(
                        choices=[
                            ("community", "Community-validated"),
                            ("vendor", "Vendor-validated"),
                            ("almalinux", "AlmaLinux-validated"),
                        ],
                        default="community",
                        max_length=16,
                    ),
                ),
                ("attestation_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TestResultAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=lumina.hardware.models._test_result_upload_to
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=300)),
                ("sha256", models.CharField(blank=True, max_length=64)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="CommunityAttestation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("community", "Community-validated"),
                            ("vendor", "Vendor-validated"),
                            ("almalinux", "AlmaLinux-validated"),
                        ],
                        default="community",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "attested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hardware_attestations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
