# Generated by Django 5.2.13 on 2026-08-04 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hardware", "0001_initial"),
        ("releases", "0001_initial"),
        ("results", "0001_initial"),
        ("taxonomy", "0001_initial"),
        ("vendors", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="communityattestation",
            name="test_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attestations",
                to="results.testrun",
            ),
        ),
        migrations.AddField(
            model_name="component",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="component",
            name="owner_vendor",
            field=models.ForeignKey(
                blank=True,
                help_text="Vendor that maintains this listing. Submit-role members of this vendor may submit edit proposals via the self-service flow. Null means no vendor maintains it (community-submitted); only admins can edit those listings.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_%(class)ss",
                to="vendors.vendor",
            ),
        ),
        migrations.AddField(
            model_name="component",
            name="vendor",
            field=models.ForeignKey(
                help_text="The hardware's manufacturer.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="vendors.vendor",
            ),
        ),
        migrations.AddField(
            model_name="communityattestation",
            name="listing_component",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attestations",
                to="hardware.component",
            ),
        ),
        migrations.AddField(
            model_name="listingcategoryvalue",
            name="listing_component",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="category_values",
                to="hardware.component",
            ),
        ),
        migrations.AddField(
            model_name="listingcategoryvalue",
            name="value",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="listing_bindings",
                to="taxonomy.categoryvalue",
            ),
        ),
        migrations.AddField(
            model_name="listingeditproposal",
            name="listing_component",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="edit_proposals",
                to="hardware.component",
            ),
        ),
        migrations.AddField(
            model_name="listingeditproposal",
            name="proposed_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="listing_edit_proposals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="listingeditproposal",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_listing_edits",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="listingversion",
            name="listing_component",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="versions",
                to="hardware.component",
            ),
        ),
        migrations.AddField(
            model_name="listingversion",
            name="release",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="releases.almalinuxrelease",
            ),
        ),
        migrations.AddField(
            model_name="communityattestation",
            name="version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attestations",
                to="hardware.listingversion",
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="listing_component",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissions",
                to="hardware.component",
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="on_behalf_of",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="submissions",
                to="vendors.vendor",
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_submissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="submitter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="submissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="communityattestation",
            name="submission",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attestations",
                to="hardware.submission",
            ),
        ),
        migrations.AddField(
            model_name="system",
            name="cpus",
            field=models.ManyToManyField(
                blank=True,
                help_text="CPU-family components certified in this system. Added automatically by approved, passing validation runs; one entry per family a run has actually proven.",
                limit_choices_to={"kind": "cpu"},
                related_name="cpu_of_systems",
                to="hardware.component",
            ),
        ),
        migrations.AddField(
            model_name="system",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="system",
            name="owner_vendor",
            field=models.ForeignKey(
                blank=True,
                help_text="Vendor that maintains this listing. Submit-role members of this vendor may submit edit proposals via the self-service flow. Null means no vendor maintains it (community-submitted); only admins can edit those listings.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_%(class)ss",
                to="vendors.vendor",
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="cited_releases",
            field=models.ManyToManyField(
                blank=True,
                related_name="hardware_submissions",
                to="releases.almalinuxrelease",
            ),
        ),
        migrations.AddField(
            model_name="system",
            name="related_components",
            field=models.ManyToManyField(
                blank=True,
                help_text="Loose cross-reference to certified components inside this system.",
                related_name="systems",
                to="hardware.component",
            ),
        ),
        migrations.AddField(
            model_name="system",
            name="supported_cpus",
            field=models.ManyToManyField(
                blank=True,
                help_text="CPU families the vendor states this system accepts, whether or not one has been validated here. A Supermicro SYS-1029U-TN10RT takes both 1st and 2nd generation Xeon Scalable; validating it with one generation says nothing about the other, so the two are recorded separately.",
                limit_choices_to={"kind": "cpu"},
                related_name="supported_in_systems",
                to="hardware.component",
            ),
        ),
        migrations.AddField(
            model_name="system",
            name="vendor",
            field=models.ForeignKey(
                help_text="The hardware's manufacturer.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="vendors.vendor",
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="listing_system",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissions",
                to="hardware.system",
            ),
        ),
        migrations.AddField(
            model_name="listingversion",
            name="listing_system",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="versions",
                to="hardware.system",
            ),
        ),
        migrations.AddField(
            model_name="listingeditproposal",
            name="listing_system",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="edit_proposals",
                to="hardware.system",
            ),
        ),
        migrations.AddField(
            model_name="listingcategoryvalue",
            name="listing_system",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="category_values",
                to="hardware.system",
            ),
        ),
        migrations.AddField(
            model_name="communityattestation",
            name="listing_system",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attestations",
                to="hardware.system",
            ),
        ),
        migrations.AddField(
            model_name="testresultattachment",
            name="submission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="hardware.submission",
            ),
        ),
        migrations.AddConstraint(
            model_name="submission",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("listing_component__isnull", True),
                        ("listing_system__isnull", False),
                    ),
                    models.Q(
                        ("listing_component__isnull", False),
                        ("listing_system__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="submission_exactly_one_listing",
            ),
        ),
        migrations.AddConstraint(
            model_name="listingversion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("listing_component__isnull", True),
                        ("listing_system__isnull", False),
                    ),
                    models.Q(
                        ("listing_component__isnull", False),
                        ("listing_system__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="listing_version_exactly_one_listing",
            ),
        ),
        migrations.AddConstraint(
            model_name="listingversion",
            constraint=models.UniqueConstraint(
                fields=("listing_system", "release"), name="unique_system_release"
            ),
        ),
        migrations.AddConstraint(
            model_name="listingversion",
            constraint=models.UniqueConstraint(
                fields=("listing_component", "release"), name="unique_component_release"
            ),
        ),
        migrations.AddConstraint(
            model_name="listingcategoryvalue",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("listing_component__isnull", True),
                        ("listing_system__isnull", False),
                    ),
                    models.Q(
                        ("listing_component__isnull", False),
                        ("listing_system__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="listing_value_exactly_one_listing",
            ),
        ),
        migrations.AddConstraint(
            model_name="listingcategoryvalue",
            constraint=models.UniqueConstraint(
                fields=("listing_system", "value"), name="unique_system_value"
            ),
        ),
        migrations.AddConstraint(
            model_name="listingcategoryvalue",
            constraint=models.UniqueConstraint(
                fields=("listing_component", "value"), name="unique_component_value"
            ),
        ),
        migrations.AddConstraint(
            model_name="communityattestation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("submission__isnull", False), ("test_run__isnull", True)),
                    models.Q(("submission__isnull", True), ("test_run__isnull", False)),
                    _connector="OR",
                ),
                name="attestation_exactly_one_source",
            ),
        ),
        migrations.AddConstraint(
            model_name="communityattestation",
            constraint=models.UniqueConstraint(
                fields=("version", "attested_by"),
                name="unique_attestation_per_version_per_user",
            ),
        ),
    ]
