"""The reference data the catalog needs to function, seeded on a fresh database.

Not sample data: these are the CPU and GPU **families** every incoming run is
classified against, and the three silicon vendors that own them. Without them
``classify_cpu`` matches nothing, the family facets are empty, and every run lands as
an unrecognised part. ``seed_devstack`` adds demonstration listings on top; this is
the floor beneath it, and a production deployment needs it too.

Five migrations used to build this up and partly undo each other - 0017 seeded the CPU
families, 0018 replaced the Xeon Scalable tiers with per-generation rows, 0022 split
Xeon E by version, 0019 and 0020 added GPUs. Collapsing that history meant taking the
*finished* state rather than replaying the steps, so the rows below were generated from
a fully migrated database rather than merged by hand.

``slug`` is carried explicitly and is not derived here. A migration operates on a bare
historical model with no custom ``save()``, so nothing would compute it, and two blank
slugs collide on the unique index - which is exactly how the first attempt at this
failed.

``get_or_create`` keyed on (vendor, name), so re-running is a no-op and a deployment
that already holds these rows is left alone. Nothing overwrites an existing row, so a
family whose patterns an operator has tuned locally keeps them.

**Deliberately not covered yet**, carried over from the migrations this replaces so a
future reader can tell an omission from a decision:

- NVIDIA data-center parts (L40S, A100, H100), the professional RTX A-series and RTX
  Ada cards, and older GeForce generations.
- Intel Arc Pro.
- AMD pre-Polaris consumer parts (HD 7000, R9 200/300), FirePro, and the embedded
  E-series.

An unmatched GPU appears under its own model name until someone adds a pattern, which
is a legible gap rather than a wrong answer.
"""
from django.db import migrations

VENDORS = [   {   'name': 'AMD',
        'published': True,
        'scope': 'hardware',
        'slug': 'amd',
        'verified': False},
    {   'name': 'Intel',
        'published': True,
        'scope': 'hardware',
        'slug': 'intel',
        'verified': False},
    {   'name': 'NVIDIA',
        'published': True,
        'scope': 'hardware',
        'slug': 'nvidia',
        'verified': False}]

COMPONENTS = [   {   'attestation_count': 0,
        'kind': 'cpu',
        'model_patterns': ['EPYC 3[0-9]{3}[A-Z]*'],
        'name': 'AMD EPYC 3000 Series',
        'published': False,
        'role': 'family',
        'slug': 'amd-amd-epyc-3000-series',
        'validation_level': 'community',
        'vendor': 'AMD'},
    {   'attestation_count': 0,
        'kind': 'cpu',
        'model_patterns': ['EPYC 4[0-9]{2}4[A-Z]*'],
        'name': 'AMD EPYC 4004 Series',
        'published': False,
        'role': 'family',
        'slug': 'amd-amd-epyc-4004-series',
        'validation_level': 'community',
        'vendor': 'AMD'},
    {   'attestation_count': 0,
        'kind': 'cpu',
        'model_patterns': ['EPYC 4[0-9]{2}5[A-Z]*'],
        'name': 'AMD EPYC 4005 Series',
        'published': False,
        'role': 'family',
        'slug': 'amd-amd-epyc-4005-series',
        'validation_level': 'community',
        'vendor': 'AMD'},
    {   'attestation_count': 0,
        'kind': 'cpu',
        'model_patterns': ['EPYC 7[0-9]{2}1[A-Z]*'],
        'name': 'AMD EPYC 7001 Series',
        'published': False,
        'role': 'family',
        'slug': 'amd-amd-epyc-7001-series',
        'validation_level': 'community',
        'vendor': 'AMD'},
    {   'attestation_count': 0,
        'kind': 'cpu',
        'model_patterns': ['EPYC 7[0-9]{2}2[A-Z]*'],
        'name': 'AMD EPYC 7002 Series',
        'published': False,
        'role': 'family',
        'slug': 'amd-amd-epyc-7002-series',
        'validation_level': 'community',
        'vendor': 'AMD'},
    {   'attestation_count': 0,
        'kind': 'cpu',
        'model_patterns': ['EPYC 7[0-9]{2}3[A-Z]*'],
        'name': 'AMD EPYC 7003 Series',
        'published': False,
        'role': 'family',
        'slug': 'amd-amd-epyc-7003-series',
        'validation_level': 'community',
        'vendor': 'AMD'},
    {   'attestation_count': 0,
        'kind': 'cpu',
        'model_patterns': ['EPYC 8[0-9]{2}4[A-Z]*'],
        'name': 'AMD EPYC 8004 Series',
        'published': False,
        'role': 'family',
        'slug': 'amd-amd-epyc-8004-series',
        'validation_level': 'community',
        'vendor': 'AMD'},
    {   'attestation_count': 0,
        'kind': 'cpu',
        'model_patterns': ['EPYC 9[0-9]{2}4[A-Z]*'],
        'name': 'AMD EPYC 9004 Series',
        'published': False,
        'role': 'family',
        'slug': 'amd-amd-epyc-9004-series',
        'validation_level': 'community',
        'vendor': 'AMD'},
    {   'attestation_count': 0,
        'kind': 'cpu',
        'model_patterns': ['EPYC 9[0-9]{2}5[A-Z]*'],
        'name': 'AMD EPYC 9005 Series',
        'published': False,
        'role': 'family',
        'slug': 'amd-amd-epyc-9005-series',
        'validation_level': 'community',
        'vendor': 'AMD'},
    {   'attestation_count': 0,
        'kind': 'gpu',
        'model_patterns': ['\\bMI100\\b'],
        'name': 'AMD Instinct MI100',
        'published': False,
        'role': 'family',
        'slug': 'amd-amd-instinct-mi100',
        'validation_level': 'community',
        'vendor': 'AMD'},
    {   'attestation_count': 0,
        'kind': 'gpu',
        'model_patterns': ['\\bMI2[0-9]{2}[A-Z]?\\b'],
        'name': 'AMD Instinct MI200 Series',
        'published': False,
        'role': 'family',
        'slug': 'amd-amd-instinct-mi200-series',
        'validation_level': 'community',
        'vendor': 'AMD'},
    {   'attestation_count': 0,
        'kind': 'gpu',
        'model_patterns': ['\\bMI3[0-9]{2}[A-Z]?\\b'],
        'name': 'AMD Instinct MI300 Series',
        'published': False,
        'role': 'family',
        'slug': 'amd-amd-instinct-mi300-series',
        'validation_level': 'community',
        'vendor': 'AMD'},
    {   'attestation_count': 0,
        'kind': 'gpu',
        'model_patterns': ['\\bRadeon 6[0-9]0M\\b'],
        'name': 'AMD Radeon 600M Series (integrated)',
        'published': False,
        'role': 'family',
        'slug': 'amd-amd-radeon-600m-series-integrated',
        'validation_level': 'community',
        'vendor': 'AMD'},
    {   'attestation_count': 0,
        'kind': 'gpu',
        'model_patterns': ['\\bRadeon 7[0-9]0M\\b'],
        'name': 'AMD Radeon 700M Series (integrated)',
        'published': False,
        'role': 'family',
        'slug': 'amd-amd-radeon-700m-series-integrated',
        'validation_level': 'community',
        'vendor': 'AMD'},
    {   'attestation_count': 0,
        'kind': 'gpu',
        'model_patterns': ['\\bRadeon 8[0-9]0M\\b'],
        'name': 'AMD Radeon 800M Series (integrated)',
        'published': False,
        'role': 'family',
        'slug': 'amd-amd-radeon-800m-series-integrated',
        'validation_level': 'community',
        'vendor': 'AMD'},
    {   'attestation_count': 0,
        'kind': 'gpu',
        'model_patterns': ['\\bRadeon Pro W[0-9]{4}\\b'],
        'name': 'AMD Radeon Pro W Series',
        'published': False,
        'role': 'family',
        'slug': 'amd-amd-radeon-pro-w-series',
        'validation_level': 'community',
        'vendor': 'AMD'},
    {   'attestation_count': 0,
        'kind': 'gpu',
        'model_patterns': ['\\bRadeon Pro WX [0-9]{4}\\b'],
        'name': 'AMD Radeon Pro WX Series',
        'published': False,
        'role': 'family',
        'slug': 'amd-amd-radeon-pro-wx-series',
        'validation_level': 'community',
        'vendor': 'AMD'},
    {   'attestation_count': 0,
        'kind': 'gpu',
        'model_patterns': ['\\bRX 4[0-9]{2}(?![0-9])'],
        'name': 'AMD Radeon RX 400 Series (Polaris)',
        'published': False,
        'role': 'family',
        'slug': 'amd-amd-radeon-rx-400-series-polaris',
        'validation_level': 'community',
        'vendor': 'AMD'},
    {   'attestation_count': 0,
        'kind': 'gpu',
        'model_patterns': ['\\bRX 5[0-9]{2}(?![0-9])'],
        'name': 'AMD Radeon RX 500 Series (Polaris)',
        'published': False,
        'role': 'family',
        'slug': 'amd-amd-radeon-rx-500-series-polaris',
        'validation_level': 'community',
        'vendor': 'AMD'},
    {   'attestation_count': 0,
        'kind': 'gpu',
        'model_patterns': ['\\bRX 5[0-9]{3}\\b'],
        'name': 'AMD Radeon RX 5000 Series (RDNA)',
        'published': False,
        'role': 'family',
        'slug': 'amd-amd-radeon-rx-5000-series-rdna',
        'validation_level': 'community',
        'vendor': 'AMD'},
    {   'attestation_count': 0,
        'kind': 'gpu',
        'model_patterns': ['\\bRX 6[0-9]{3}\\b'],
        'name': 'AMD Radeon RX 6000 Series (RDNA 2)',
        'published': False,
        'role': 'family',
        'slug': 'amd-amd-radeon-rx-6000-series-rdna-2',
        'validation_level': 'community',
        'vendor': 'AMD'},
    {   'attestation_count': 0,
        'kind': 'gpu',
        'model_patterns': ['\\bRX 7[0-9]{3}\\b'],
        'name': 'AMD Radeon RX 7000 Series (RDNA 3)',
        'published': False,
        'role': 'family',
        'slug': 'amd-amd-radeon-rx-7000-series-rdna-3',
        'validation_level': 'community',
        'vendor': 'AMD'},
    {   'attestation_count': 0,
        'kind': 'gpu',
        'model_patterns': ['\\bRX 9[0-9]{3}\\b'],
        'name': 'AMD Radeon RX 9000 Series (RDNA 4)',
        'published': False,
        'role': 'family',
        'slug': 'amd-amd-radeon-rx-9000-series-rdna-4',
        'validation_level': 'community',
        'vendor': 'AMD'},
    {   'attestation_count': 0,
        'kind': 'gpu',
        'model_patterns': ['\\bRX Vega (?:56|64)\\b'],
        'name': 'AMD Radeon RX Vega Series',
        'published': False,
        'role': 'family',
        'slug': 'amd-amd-radeon-rx-vega-series',
        'validation_level': 'community',
        'vendor': 'AMD'},
    {   'attestation_count': 0,
        'kind': 'gpu',
        'model_patterns': ['\\bRadeon (?:RX )?Vega (?:1[01]|[36789])\\b'],
        'name': 'AMD Radeon Vega Graphics (integrated)',
        'published': False,
        'role': 'family',
        'slug': 'amd-amd-radeon-vega-graphics-integrated',
        'validation_level': 'community',
        'vendor': 'AMD'},
    {   'attestation_count': 0,
        'kind': 'cpu',
        'model_patterns': ['Ryzen [3579]( PRO)? 1[0-9]{3}(?![0-9])'],
        'name': 'AMD Ryzen 1000 Series',
        'published': False,
        'role': 'family',
        'slug': 'amd-amd-ryzen-1000-series',
        'validation_level': 'community',
        'vendor': 'AMD'},
    {   'attestation_count': 0,
        'kind': 'cpu',
        'model_patterns': ['Ryzen [3579]( PRO)? 2[0-9]{3}(?![0-9])'],
        'name': 'AMD Ryzen 2000 Series',
        'published': False,
        'role': 'family',
        'slug': 'amd-amd-ryzen-2000-series',
        'validation_level': 'community',
        'vendor': 'AMD'},
    {   'attestation_count': 0,
        'kind': 'cpu',
        'model_patterns': ['Ryzen [3579]( PRO)? 3[0-9]{3}(?![0-9])'],
        'name': 'AMD Ryzen 3000 Series',
        'published': False,
        'role': 'family',
        'slug': 'amd-amd-ryzen-3000-series',
        'validation_level': 'community',
        'vendor': 'AMD'},
    {   'attestation_count': 0,
        'kind': 'cpu',
        'model_patterns': ['Ryzen [3579]( PRO)? 4[0-9]{3}(?![0-9])'],
        'name': 'AMD Ryzen 4000 Series',
        'published': False,
        'role': 'family',
        'slug': 'amd-amd-ryzen-4000-series',
        'validation_level': 'community',
        'vendor': 'AMD'},
    {   'attestation_count': 0,
        'kind': 'cpu',
        'model_patterns': ['Ryzen [3579]( PRO)? 5[0-9]{3}(?![0-9])'],
        'name': 'AMD Ryzen 5000 Series',
        'published': False,
        'role': 'family',
        'slug': 'amd-amd-ryzen-5000-series',
        'validation_level': 'community',
        'vendor': 'AMD'},
    {   'attestation_count': 0,
        'kind': 'cpu',
        'model_patterns': ['Ryzen [3579]( PRO)? 6[0-9]{3}(?![0-9])'],
        'name': 'AMD Ryzen 6000 Series',
        'published': False,
        'role': 'family',
        'slug': 'amd-amd-ryzen-6000-series',
        'validation_level': 'community',
        'vendor': 'AMD'},
    {   'attestation_count': 0,
        'kind': 'cpu',
        'model_patterns': ['Ryzen [3579]( PRO)? 7[0-9]{3}(?![0-9])'],
        'name': 'AMD Ryzen 7000 Series',
        'published': False,
        'role': 'family',
        'slug': 'amd-amd-ryzen-7000-series',
        'validation_level': 'community',
        'vendor': 'AMD'},
    {   'attestation_count': 0,
        'kind': 'cpu',
        'model_patterns': ['Ryzen [3579]( PRO)? 8[0-9]{3}(?![0-9])'],
        'name': 'AMD Ryzen 8000 Series',
        'published': False,
        'role': 'family',
        'slug': 'amd-amd-ryzen-8000-series',
        'validation_level': 'community',
        'vendor': 'AMD'},
    {   'attestation_count': 0,
        'kind': 'cpu',
        'model_patterns': ['Ryzen [3579]( PRO)? 9[0-9]{3}(?![0-9])'],
        'name': 'AMD Ryzen 9000 Series',
        'published': False,
        'role': 'family',
        'slug': 'amd-amd-ryzen-9000-series',
        'validation_level': 'community',
        'vendor': 'AMD'},
    {   'attestation_count': 0,
        'kind': 'cpu',
        'model_patterns': ['Ryzen AI [3579]( HX)? 3[0-9]{2}'],
        'name': 'AMD Ryzen AI 300 Series',
        'published': False,
        'role': 'family',
        'slug': 'amd-amd-ryzen-ai-300-series',
        'validation_level': 'community',
        'vendor': 'AMD'},
    {   'attestation_count': 0,
        'kind': 'cpu',
        'model_patterns': ['Threadripper( PRO)? 1[0-9]{3}'],
        'name': 'AMD Ryzen Threadripper 1000 Series',
        'published': False,
        'role': 'family',
        'slug': 'amd-amd-ryzen-threadripper-1000-series',
        'validation_level': 'community',
        'vendor': 'AMD'},
    {   'attestation_count': 0,
        'kind': 'cpu',
        'model_patterns': ['Threadripper( PRO)? 2[0-9]{3}'],
        'name': 'AMD Ryzen Threadripper 2000 Series',
        'published': False,
        'role': 'family',
        'slug': 'amd-amd-ryzen-threadripper-2000-series',
        'validation_level': 'community',
        'vendor': 'AMD'},
    {   'attestation_count': 0,
        'kind': 'cpu',
        'model_patterns': ['Threadripper( PRO)? 3[0-9]{3}'],
        'name': 'AMD Ryzen Threadripper 3000 Series',
        'published': False,
        'role': 'family',
        'slug': 'amd-amd-ryzen-threadripper-3000-series',
        'validation_level': 'community',
        'vendor': 'AMD'},
    {   'attestation_count': 0,
        'kind': 'cpu',
        'model_patterns': ['Threadripper( PRO)? 5[0-9]{3}'],
        'name': 'AMD Ryzen Threadripper 5000 Series',
        'published': False,
        'role': 'family',
        'slug': 'amd-amd-ryzen-threadripper-5000-series',
        'validation_level': 'community',
        'vendor': 'AMD'},
    {   'attestation_count': 0,
        'kind': 'cpu',
        'model_patterns': ['Threadripper( PRO)? 7[0-9]{3}'],
        'name': 'AMD Ryzen Threadripper 7000 Series',
        'published': False,
        'role': 'family',
        'slug': 'amd-amd-ryzen-threadripper-7000-series',
        'validation_level': 'community',
        'vendor': 'AMD'},
    {   'attestation_count': 0,
        'kind': 'cpu',
        'model_patterns': ['Threadripper( PRO)? 9[0-9]{3}'],
        'name': 'AMD Ryzen Threadripper 9000 Series',
        'published': False,
        'role': 'family',
        'slug': 'amd-amd-ryzen-threadripper-9000-series',
        'validation_level': 'community',
        'vendor': 'AMD'},
    {   'attestation_count': 0,
        'kind': 'gpu',
        'model_patterns': ['Arc A[0-9]{3}M?\\b'],
        'name': 'Intel Arc A-Series (Alchemist)',
        'published': False,
        'role': 'family',
        'slug': 'intel-intel-arc-a-series-alchemist',
        'validation_level': 'community',
        'vendor': 'Intel'},
    {   'attestation_count': 0,
        'kind': 'gpu',
        'model_patterns': ['Arc B[0-9]{3}M?\\b'],
        'name': 'Intel Arc B-Series (Battlemage)',
        'published': False,
        'role': 'family',
        'slug': 'intel-intel-arc-b-series-battlemage',
        'validation_level': 'community',
        'vendor': 'Intel'},
    {   'attestation_count': 0,
        'kind': 'cpu',
        'model_patterns': ['i[3579]-10[0-9]{2,3}(?![0-9])'],
        'name': 'Intel Core 10th Generation',
        'published': False,
        'role': 'family',
        'slug': 'intel-intel-core-10th-generation',
        'validation_level': 'community',
        'vendor': 'Intel'},
    {   'attestation_count': 0,
        'kind': 'cpu',
        'model_patterns': ['i[3579]-11[0-9]{2,3}(?![0-9])'],
        'name': 'Intel Core 11th Generation',
        'published': False,
        'role': 'family',
        'slug': 'intel-intel-core-11th-generation',
        'validation_level': 'community',
        'vendor': 'Intel'},
    {   'attestation_count': 0,
        'kind': 'cpu',
        'model_patterns': ['i[3579]-12[0-9]{2,3}(?![0-9])'],
        'name': 'Intel Core 12th Generation',
        'published': False,
        'role': 'family',
        'slug': 'intel-intel-core-12th-generation',
        'validation_level': 'community',
        'vendor': 'Intel'},
    {   'attestation_count': 0,
        'kind': 'cpu',
        'model_patterns': ['i[3579]-13[0-9]{2,3}(?![0-9])'],
        'name': 'Intel Core 13th Generation',
        'published': False,
        'role': 'family',
        'slug': 'intel-intel-core-13th-generation',
        'validation_level': 'community',
        'vendor': 'Intel'},
    {   'attestation_count': 0,
        'kind': 'cpu',
        'model_patterns': ['i[3579]-14[0-9]{2,3}(?![0-9])'],
        'name': 'Intel Core 14th Generation',
        'published': False,
        'role': 'family',
        'slug': 'intel-intel-core-14th-generation',
        'validation_level': 'community',
        'vendor': 'Intel'},
    {   'attestation_count': 0,
        'kind': 'cpu',
        'model_patterns': ['i[3579]-2[0-9]{3}(?![0-9])'],
        'name': 'Intel Core 2nd Generation',
        'published': False,
        'role': 'family',
        'slug': 'intel-intel-core-2nd-generation',
        'validation_level': 'community',
        'vendor': 'Intel'},
    {   'attestation_count': 0,
        'kind': 'cpu',
        'model_patterns': ['i[3579]-3[0-9]{3}(?![0-9])'],
        'name': 'Intel Core 3rd Generation',
        'published': False,
        'role': 'family',
        'slug': 'intel-intel-core-3rd-generation',
        'validation_level': 'community',
        'vendor': 'Intel'},
    {   'attestation_count': 0,
        'kind': 'cpu',
        'model_patterns': ['i[3579]-4[0-9]{3}(?![0-9])'],
        'name': 'Intel Core 4th Generation',
        'published': False,
        'role': 'family',
        'slug': 'intel-intel-core-4th-generation',
        'validation_level': 'community',
        'vendor': 'Intel'},
    {   'attestation_count': 0,
        'kind': 'cpu',
        'model_patterns': ['i[3579]-5[0-9]{3}(?![0-9])'],
        'name': 'Intel Core 5th Generation',
        'published': False,
        'role': 'family',
        'slug': 'intel-intel-core-5th-generation',
        'validation_level': 'community',
        'vendor': 'Intel'},
    {   'attestation_count': 0,
        'kind': 'cpu',
        'model_patterns': ['i[3579]-6[0-9]{3}(?![0-9])'],
        'name': 'Intel Core 6th Generation',
        'published': False,
        'role': 'family',
        'slug': 'intel-intel-core-6th-generation',
        'validation_level': 'community',
        'vendor': 'Intel'},
    {   'attestation_count': 0,
        'kind': 'cpu',
        'model_patterns': ['i[3579]-7[0-9]{3}(?![0-9])'],
        'name': 'Intel Core 7th Generation',
        'published': False,
        'role': 'family',
        'slug': 'intel-intel-core-7th-generation',
        'validation_level': 'community',
        'vendor': 'Intel'},
    {   'attestation_count': 0,
        'kind': 'cpu',
        'model_patterns': ['i[3579]-8[0-9]{3}(?![0-9])'],
        'name': 'Intel Core 8th Generation',
        'published': False,
        'role': 'family',
        'slug': 'intel-intel-core-8th-generation',
        'validation_level': 'community',
        'vendor': 'Intel'},
    {   'attestation_count': 0,
        'kind': 'cpu',
        'model_patterns': ['i[3579]-9[0-9]{3}(?![0-9])'],
        'name': 'Intel Core 9th Generation',
        'published': False,
        'role': 'family',
        'slug': 'intel-intel-core-9th-generation',
        'validation_level': 'community',
        'vendor': 'Intel'},
    {   'attestation_count': 0,
        'kind': 'cpu',
        'model_patterns': ['Core Ultra [3579] 1[0-9]{2}'],
        'name': 'Intel Core Ultra Series 1',
        'published': False,
        'role': 'family',
        'slug': 'intel-intel-core-ultra-series-1',
        'validation_level': 'community',
        'vendor': 'Intel'},
    {   'attestation_count': 0,
        'kind': 'cpu',
        'model_patterns': ['Core Ultra [3579] 2[0-9]{2}'],
        'name': 'Intel Core Ultra Series 2',
        'published': False,
        'role': 'family',
        'slug': 'intel-intel-core-ultra-series-2',
        'validation_level': 'community',
        'vendor': 'Intel'},
    {   'attestation_count': 0,
        'kind': 'cpu',
        'model_patterns': ['Xeon 6[0-9]{3}[A-Z]'],
        'name': 'Intel Xeon 6',
        'published': False,
        'role': 'family',
        'slug': 'intel-intel-xeon-6',
        'validation_level': 'community',
        'vendor': 'Intel'},
    {   'attestation_count': 0,
        'kind': 'cpu',
        'model_patterns': ['Xeon D-[0-9]{4}'],
        'name': 'Intel Xeon D Family',
        'published': False,
        'role': 'family',
        'slug': 'intel-intel-xeon-d-family',
        'validation_level': 'community',
        'vendor': 'Intel'},
    {   'attestation_count': 0,
        'kind': 'cpu',
        'model_patterns': ['Xeon E-2[0-9]{3}'],
        'name': 'Intel Xeon E Family',
        'published': False,
        'role': 'family',
        'slug': 'intel-intel-xeon-e-family',
        'validation_level': 'community',
        'vendor': 'Intel'},
    {   'attestation_count': 0,
        'kind': 'cpu',
        'model_patterns': ['Xeon E3-[0-9]{4}(?!\\s*v[0-9])'],
        'name': 'Intel Xeon E3 v1 Family (Sandy Bridge)',
        'published': False,
        'role': 'family',
        'slug': 'intel-intel-xeon-e3-v1-family-sandy-bridge',
        'validation_level': 'community',
        'vendor': 'Intel'},
    {   'attestation_count': 0,
        'kind': 'cpu',
        'model_patterns': ['Xeon E3-[0-9]{4}\\s*v2\\b'],
        'name': 'Intel Xeon E3 v2 Family (Ivy Bridge)',
        'published': False,
        'role': 'family',
        'slug': 'intel-intel-xeon-e3-v2-family-ivy-bridge',
        'validation_level': 'community',
        'vendor': 'Intel'},
    {   'attestation_count': 0,
        'kind': 'cpu',
        'model_patterns': ['Xeon E3-[0-9]{4}\\s*v3\\b'],
        'name': 'Intel Xeon E3 v3 Family (Haswell)',
        'published': False,
        'role': 'family',
        'slug': 'intel-intel-xeon-e3-v3-family-haswell',
        'validation_level': 'community',
        'vendor': 'Intel'},
    {   'attestation_count': 0,
        'kind': 'cpu',
        'model_patterns': ['Xeon E3-[0-9]{4}\\s*v4\\b'],
        'name': 'Intel Xeon E3 v4 Family (Broadwell)',
        'published': False,
        'role': 'family',
        'slug': 'intel-intel-xeon-e3-v4-family-broadwell',
        'validation_level': 'community',
        'vendor': 'Intel'},
    {   'attestation_count': 0,
        'kind': 'cpu',
        'model_patterns': ['Xeon E3-[0-9]{4}\\s*v5\\b'],
        'name': 'Intel Xeon E3 v5 Family (Skylake)',
        'published': False,
        'role': 'family',
        'slug': 'intel-intel-xeon-e3-v5-family-skylake',
        'validation_level': 'community',
        'vendor': 'Intel'},
    {   'attestation_count': 0,
        'kind': 'cpu',
        'model_patterns': ['Xeon E3-[0-9]{4}\\s*v6\\b'],
        'name': 'Intel Xeon E3 v6 Family (Kaby Lake)',
        'published': False,
        'role': 'family',
        'slug': 'intel-intel-xeon-e3-v6-family-kaby-lake',
        'validation_level': 'community',
        'vendor': 'Intel'},
    {   'attestation_count': 0,
        'kind': 'cpu',
        'model_patterns': ['Xeon E5-[0-9]{4}(?!\\s*v[0-9])'],
        'name': 'Intel Xeon E5 v1 Family (Sandy Bridge-EP)',
        'published': False,
        'role': 'family',
        'slug': 'intel-intel-xeon-e5-v1-family-sandy-bridge-ep',
        'validation_level': 'community',
        'vendor': 'Intel'},
    {   'attestation_count': 0,
        'kind': 'cpu',
        'model_patterns': ['Xeon E5-[0-9]{4}\\s*v2\\b'],
        'name': 'Intel Xeon E5 v2 Family (Ivy Bridge-EP)',
        'published': False,
        'role': 'family',
        'slug': 'intel-intel-xeon-e5-v2-family-ivy-bridge-ep',
        'validation_level': 'community',
        'vendor': 'Intel'},
    {   'attestation_count': 0,
        'kind': 'cpu',
        'model_patterns': ['Xeon E5-[0-9]{4}\\s*v3\\b'],
        'name': 'Intel Xeon E5 v3 Family (Haswell-EP)',
        'published': False,
        'role': 'family',
        'slug': 'intel-intel-xeon-e5-v3-family-haswell-ep',
        'validation_level': 'community',
        'vendor': 'Intel'},
    {   'attestation_count': 0,
        'kind': 'cpu',
        'model_patterns': ['Xeon E5-[0-9]{4}\\s*v4\\b'],
        'name': 'Intel Xeon E5 v4 Family (Broadwell-EP)',
        'published': False,
        'role': 'family',
        'slug': 'intel-intel-xeon-e5-v4-family-broadwell-ep',
        'validation_level': 'community',
        'vendor': 'Intel'},
    {   'attestation_count': 0,
        'kind': 'cpu',
        'model_patterns': ['Xeon E7-[0-9]{4}(?!\\s*v[0-9])'],
        'name': 'Intel Xeon E7 v1 Family (Westmere-EX)',
        'published': False,
        'role': 'family',
        'slug': 'intel-intel-xeon-e7-v1-family-westmere-ex',
        'validation_level': 'community',
        'vendor': 'Intel'},
    {   'attestation_count': 0,
        'kind': 'cpu',
        'model_patterns': ['Xeon E7-[0-9]{4}\\s*v2\\b'],
        'name': 'Intel Xeon E7 v2 Family (Ivy Bridge-EX)',
        'published': False,
        'role': 'family',
        'slug': 'intel-intel-xeon-e7-v2-family-ivy-bridge-ex',
        'validation_level': 'community',
        'vendor': 'Intel'},
    {   'attestation_count': 0,
        'kind': 'cpu',
        'model_patterns': ['Xeon E7-[0-9]{4}\\s*v3\\b'],
        'name': 'Intel Xeon E7 v3 Family (Haswell-EX)',
        'published': False,
        'role': 'family',
        'slug': 'intel-intel-xeon-e7-v3-family-haswell-ex',
        'validation_level': 'community',
        'vendor': 'Intel'},
    {   'attestation_count': 0,
        'kind': 'cpu',
        'model_patterns': ['Xeon E7-[0-9]{4}\\s*v4\\b'],
        'name': 'Intel Xeon E7 v4 Family (Broadwell-EX)',
        'published': False,
        'role': 'family',
        'slug': 'intel-intel-xeon-e7-v4-family-broadwell-ex',
        'validation_level': 'community',
        'vendor': 'Intel'},
    {   'attestation_count': 0,
        'kind': 'cpu',
        'model_patterns': ['Xeon (Platinum|Gold|Silver|Bronze) [3-9]1[0-9]{2}'],
        'name': 'Intel Xeon Scalable 1st Generation',
        'published': False,
        'role': 'family',
        'slug': 'intel-intel-xeon-scalable-1st-generation',
        'validation_level': 'community',
        'vendor': 'Intel'},
    {   'attestation_count': 0,
        'kind': 'cpu',
        'model_patterns': ['Xeon (Platinum|Gold|Silver|Bronze) [3-9]2[0-9]{2}'],
        'name': 'Intel Xeon Scalable 2nd Generation',
        'published': False,
        'role': 'family',
        'slug': 'intel-intel-xeon-scalable-2nd-generation',
        'validation_level': 'community',
        'vendor': 'Intel'},
    {   'attestation_count': 0,
        'kind': 'cpu',
        'model_patterns': ['Xeon (Platinum|Gold|Silver|Bronze) [3-9]3[0-9]{2}'],
        'name': 'Intel Xeon Scalable 3rd Generation',
        'published': False,
        'role': 'family',
        'slug': 'intel-intel-xeon-scalable-3rd-generation',
        'validation_level': 'community',
        'vendor': 'Intel'},
    {   'attestation_count': 0,
        'kind': 'cpu',
        'model_patterns': ['Xeon (Platinum|Gold|Silver|Bronze) [3-9]4[0-9]{2}'],
        'name': 'Intel Xeon Scalable 4th Generation',
        'published': False,
        'role': 'family',
        'slug': 'intel-intel-xeon-scalable-4th-generation',
        'validation_level': 'community',
        'vendor': 'Intel'},
    {   'attestation_count': 0,
        'kind': 'cpu',
        'model_patterns': ['Xeon (Platinum|Gold|Silver|Bronze) [3-9]5[0-9]{2}'],
        'name': 'Intel Xeon Scalable 5th Generation',
        'published': False,
        'role': 'family',
        'slug': 'intel-intel-xeon-scalable-5th-generation',
        'validation_level': 'community',
        'vendor': 'Intel'},
    {   'attestation_count': 0,
        'kind': 'cpu',
        'model_patterns': ['Xeon W-[0-9]{4}', 'Xeon w[3579]-[0-9]{4}'],
        'name': 'Intel Xeon W Family',
        'published': False,
        'role': 'family',
        'slug': 'intel-intel-xeon-w-family',
        'validation_level': 'community',
        'vendor': 'Intel'},
    {   'attestation_count': 0,
        'kind': 'gpu',
        'model_patterns': ['GTX 16[0-9]0'],
        'name': 'NVIDIA GeForce GTX 16 Series',
        'published': False,
        'role': 'family',
        'slug': 'nvidia-nvidia-geforce-gtx-16-series',
        'validation_level': 'community',
        'vendor': 'NVIDIA'},
    {   'attestation_count': 0,
        'kind': 'gpu',
        'model_patterns': ['RTX 20[5-9]0'],
        'name': 'NVIDIA GeForce RTX 20 Series',
        'published': False,
        'role': 'family',
        'slug': 'nvidia-nvidia-geforce-rtx-20-series',
        'validation_level': 'community',
        'vendor': 'NVIDIA'},
    {   'attestation_count': 0,
        'kind': 'gpu',
        'model_patterns': ['RTX 30[5-9]0'],
        'name': 'NVIDIA GeForce RTX 30 Series',
        'published': False,
        'role': 'family',
        'slug': 'nvidia-nvidia-geforce-rtx-30-series',
        'validation_level': 'community',
        'vendor': 'NVIDIA'},
    {   'attestation_count': 0,
        'kind': 'gpu',
        'model_patterns': ['RTX 40[5-9]0'],
        'name': 'NVIDIA GeForce RTX 40 Series',
        'published': False,
        'role': 'family',
        'slug': 'nvidia-nvidia-geforce-rtx-40-series',
        'validation_level': 'community',
        'vendor': 'NVIDIA'},
    {   'attestation_count': 0,
        'kind': 'gpu',
        'model_patterns': ['RTX 50[5-9]0'],
        'name': 'NVIDIA GeForce RTX 50 Series',
        'published': False,
        'role': 'family',
        'slug': 'nvidia-nvidia-geforce-rtx-50-series',
        'validation_level': 'community',
        'vendor': 'NVIDIA'}]


def seed(apps, schema_editor):
    Vendor = apps.get_model("vendors", "Vendor")
    Component = apps.get_model("hardware", "Component")

    vendors = {}
    for row in VENDORS:
        fields = dict(row)
        name = fields.pop("name")
        vendor, _ = Vendor.objects.get_or_create(name=name, defaults=fields)
        vendors[name] = vendor

    for row in COMPONENTS:
        fields = dict(row)
        vendor = vendors.get(fields.pop("vendor"))
        Component.objects.get_or_create(
            vendor=vendor, name=fields.pop("name"), defaults=fields,
        )


def unseed(apps, schema_editor):
    """Reversible only as far as the rows this migration is responsible for.

    Deletes the families, not the vendors: by the time anyone reverses this a vendor
    may own real listings, and cascading those away to undo a seed would be a far
    larger action than undoing a seed should be.
    """
    Component = apps.get_model("hardware", "Component")
    for row in COMPONENTS:
        Component.objects.filter(
            vendor__name=row["vendor"], name=row["name"], role="family",
        ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("hardware", "0002_initial"),
        ("vendors", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed, unseed),
    ]
