# Generated by Django 5.2.13 on 2026-08-12 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hardware", "0003_reference_data"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="listingversion",
            options={"ordering": ["-release__major"]},
        ),
        migrations.RemoveField(
            model_name="listingversion",
            name="minimum_minor",
        ),
    ]
