# Generated by Django 5.2.13 on 2026-08-12 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hardware", "0004_drop_listing_version_minimum_minor"),
    ]

    operations = [
        migrations.AddField(
            model_name="listingversion",
            name="available_from_minor",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="The minor of this major in which the hardware enablement lands, when the evidence came from AlmaLinux Kitten. The listing is published and carries a disclaimer naming this minor until ``AlmaLinuxRelease.latest_minor`` reaches it. Null means the claim is live.",
                null=True,
            ),
        ),
    ]
