# Generated by Django 5.2.13 on 2026-08-26 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hardware", "0005_listingversion_available_from_minor"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComponentExclusionRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vendor_id",
                    models.CharField(
                        blank=True,
                        help_text="PCI vendor id, 4 hex digits (e.g. 1a03). Blank matches any vendor.",
                        max_length=4,
                    ),
                ),
                (
                    "device_id",
                    models.CharField(
                        blank=True,
                        help_text="PCI device id, 4 hex digits (e.g. 164e). Blank matches any device of the vendor.",
                        max_length=4,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("cpu", "CPU"),
                            ("motherboard", "Motherboard"),
                            ("gpu", "GPU"),
                            ("nic", "NIC"),
                            ("storage", "Storage"),
                            ("management", "Management"),
                            ("other", "Other"),
                        ],
                        help_text="Restrict to one component kind. Blank matches any.",
                        max_length=16,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        help_text="Shown beside the excluded device on the review screen, e.g. 'onboard iGPU, not the accelerator under test'.",
                        max_length=200,
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["vendor_id", "device_id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("vendor_id", "device_id", "kind"),
                        name="unique_component_exclusion_rule",
                    )
                ],
            },
        ),
    ]
