# Generated by Django 5.2.13 on 2026-09-22 18:09

from django.db import migrations, models


def backfill(apps, schema_editor):
    """Fill the column from the attestations already recorded.

    Without this every listing in an existing catalog sorts as never certified, which on the
    browse page means the ordering this was added for shows nothing until somebody certifies
    something new.

    Max over the attestations rather than ``recompute_listing_levels``: that function is the
    real writer and belongs to the live models, and a data migration that calls into live code
    breaks the day the model moves on. The value is the same one it computes.
    """
    from django.db.models import Max

    for name, column in (("System", "listing_system"), ("Component", "listing_component")):
        model = apps.get_model("hardware", name)
        attestation = apps.get_model("hardware", "CommunityAttestation")
        stamps = dict(
            attestation.objects.values_list(column)
            .annotate(last=Max("created_at"))
            .values_list(column, "last")
        )
        for pk, last in stamps.items():
            if pk is not None:
                model.objects.filter(pk=pk).update(last_certified_at=last)


def unbackfill(apps, schema_editor):
    """Nothing to undo: the column goes with the reverse of the AddField above."""


class Migration(migrations.Migration):

    dependencies = [
        ("hardware", "0005_seed_name_suggestion_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="component",
            name="last_certified_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="system",
            name="last_certified_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.RunPython(backfill, unbackfill),
    ]
