# Generated by Django 5.2.13 on 2026-08-31 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hardware", "0006_componentexclusionrule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="component",
            name="model_patterns",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="One regular expression per line, matched case-insensitively against reported model strings. Leave empty for a specific model rather than a family. Keep a family to a single generation and socket: certifying one member certifies every model the patterns match, so a pattern spanning sockets (e.g. all “Xeon E” generations, which change socket across E-2100/2200/2300/2400) would certify hardware the run never ran on. Prefer per-generation families like “Xeon E-2300 Series”.",
            ),
        ),
    ]
