# Generated by Django 5.2.13 on 2026-09-25 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hardware", "0006_listing_last_certified_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="component",
            name="vendor_spec_url",
            field=models.URLField(
                blank=True,
                help_text="Link to the vendor's spec sheet for this listing. Surfaced as a CTA on the public detail page.",
                max_length=2048,
            ),
        ),
        migrations.AlterField(
            model_name="listingeditproposal",
            name="vendor_spec_url",
            field=models.URLField(blank=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name="system",
            name="vendor_spec_url",
            field=models.URLField(
                blank=True,
                help_text="Link to the vendor's spec sheet for this listing. Surfaced as a CTA on the public detail page.",
                max_length=2048,
            ),
        ),
    ]
