# Generated by Django 5.2.13 on 2026-09-15 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hardware", "0007_alter_component_model_patterns"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ComponentNamingRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("cpu", "CPU"),
                            ("motherboard", "Motherboard"),
                            ("gpu", "GPU"),
                            ("nic", "NIC"),
                            ("storage", "Storage"),
                            ("management", "Management"),
                            ("other", "Other"),
                        ],
                        help_text="Restrict to one component kind. Blank matches any.",
                        max_length=16,
                    ),
                ),
                (
                    "vendor",
                    models.CharField(
                        blank=True,
                        help_text="Substring of the resolved vendor name, case-insensitive (e.g. Ampere). Blank matches any vendor.",
                        max_length=120,
                    ),
                ),
                (
                    "model_pattern",
                    models.CharField(
                        blank=True,
                        help_text="Regular expression the reported model must match, case-insensitive (e.g. ^Altra). Captures are available to the template as match.1, match.2.",
                        max_length=200,
                    ),
                ),
                (
                    "vendor_id",
                    models.CharField(
                        blank=True,
                        help_text="PCI vendor id, 4 hex digits. Blank matches any.",
                        max_length=4,
                    ),
                ),
                (
                    "device_id",
                    models.CharField(
                        blank=True,
                        help_text="PCI device id, 4 hex digits. Blank matches any.",
                        max_length=4,
                    ),
                ),
                (
                    "conditions",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Extra tests, all of which must hold: [{"field": "cpu.model", "op": "icontains", "value": "Altra"}]. Fields are the same names the template reads.',
                    ),
                ),
                (
                    "build",
                    models.TextField(
                        help_text="Jinja template for the name, e.g. {{ dmi.processor[0]['Part Number'] }}."
                    ),
                ),
                (
                    "fallback",
                    models.TextField(
                        blank=True,
                        help_text="Used when the template above renders empty - the machine did not report the field it needs. Compose something that still distinguishes the part, e.g. {{ model }} ({{ cpu.cores }}-core).",
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=100,
                        help_text="Lowest first. Leave room between rules (10, 20, 30) so one can be inserted between two later without renumbering.",
                    ),
                ),
                (
                    "built_in",
                    models.BooleanField(
                        default=False,
                        help_text="Shipped with lumina, reproducing behaviour that used to be in code. Editable, but a change here changes how every machine of that shape is named.",
                    ),
                ),
                (
                    "notes",
                    models.CharField(
                        blank=True,
                        help_text="Why this rule exists, for whoever reads it next.",
                        max_length=300,
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["priority", "id"],
            },
        ),
    ]
