# Generated by Django 5.2.13 on 2026-09-15 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hardware", "0009_seed_naming_rules"),
    ]

    operations = [
        migrations.AddField(
            model_name="component",
            name="named_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="named_components",
                to="hardware.componentnamingrule",
            ),
        ),
    ]
