# Generated by Django 5.2.13 on 2026-09-16 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hardware", "0011_naming_rule_conditions"),
    ]

    operations = [
        migrations.AddField(
            model_name="componentnamingrule",
            name="match_field",
            field=models.CharField(
                blank=True,
                help_text="Which field the pattern below runs against. Blank means the part's own model. Any path a template can read, e.g. cpu.model.",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="componentnamingrule",
            name="model_pattern",
            field=models.CharField(
                blank=True,
                help_text="Regular expression the field above must match, case-insensitive (e.g. ^Altra). Its captures are what the template reads as match.1, match.2, which is why this is a field of its own rather than a condition.",
                max_length=200,
            ),
        ),
    ]
