# Generated by Django 5.2.13 on 2026-09-17 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hardware", "0013_naming_rules_do_their_own_regex"),
    ]

    operations = [
        migrations.CreateModel(
            name="NameSuggestionField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("cpu", "CPU"),
                            ("motherboard", "Motherboard"),
                            ("gpu", "GPU"),
                            ("nic", "NIC"),
                            ("storage", "Storage"),
                            ("management", "Management"),
                            ("other", "Other"),
                        ],
                        help_text="The component kind this field is offered for.",
                        max_length=16,
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        help_text="Where the value is, in the same paths a naming rule reads. Use * for a list index: dmi.processor.*.Part Number",
                        max_length=200,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text='What to call it when it is offered, e.g. "Processor part number". Shown under the value, so it only has to tell two similar values apart.',
                        max_length=80,
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=100,
                        help_text="Lowest first, which is the order they are offered in.",
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                (
                    "built_in",
                    models.BooleanField(
                        default=False,
                        help_text="Shipped with lumina. Editable, like any other row.",
                    ),
                ),
            ],
            options={
                "ordering": ["kind", "priority", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("kind", "path"), name="unique_suggestion_field"
                    )
                ],
            },
        ),
    ]
