# Generated by Django 5.2.13 on 2026-08-04 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AlmaLinuxRelease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("major", models.PositiveSmallIntegerField(unique=True)),
                (
                    "supported",
                    models.BooleanField(
                        default=True,
                        help_text="False for EOL releases. Excluded from supported() queryset.",
                    ),
                ),
                (
                    "max_minor",
                    models.PositiveSmallIntegerField(
                        default=10,
                        help_text="Highest minor offered in compatibility dropdowns for this major. Per-major rather than global because release cadences differ and nothing guarantees a major stops at .10. Raise it here when a new minor ships; a run reporting a higher minor than this is still recorded, and extends its own dropdown.",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "AlmaLinux release",
                "verbose_name_plural": "AlmaLinux releases",
                "ordering": ["-major"],
            },
        ),
    ]
