# Generated by Django 5.2.13 on 2026-09-18 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AlmaLinuxRelease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("major", models.PositiveSmallIntegerField(unique=True)),
                (
                    "supported",
                    models.BooleanField(
                        default=True,
                        help_text="False for EOL releases. Excluded from supported() queryset.",
                    ),
                ),
                (
                    "latest_minor",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        default=None,
                        help_text="The newest minor of this major that has shipped. Raise it here when a new minor is released. Leave it EMPTY while the major itself has not been released at all - which is not the same as 0, and is the normal state for a major that AlmaLinux Kitten is tracking months before its first stable release. This is what lifts the disclaimer on hardware proved on Kitten.",
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "AlmaLinux release",
                "verbose_name_plural": "AlmaLinux releases",
                "ordering": ["-major"],
            },
        ),
    ]
