# Generated by Django 5.2.13 on 2026-08-12 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("releases", "0002_latest_minor_and_kitten_target"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="almalinuxrelease",
            name="kitten_target_major",
        ),
    ]
