# Generated by Django 5.2.13 on 2026-08-12 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("releases", "0003_drop_kitten_target_major"),
    ]

    operations = [
        migrations.AlterField(
            model_name="almalinuxrelease",
            name="latest_minor",
            field=models.PositiveSmallIntegerField(
                blank=True,
                default=None,
                help_text="The newest minor of this major that has shipped. Raise it here when a new minor is released. Leave it EMPTY while the major itself has not been released at all - which is not the same as 0, and is the normal state for a major that AlmaLinux Kitten is tracking months before its first stable release. This is what lifts the disclaimer on hardware proved on Kitten.",
                null=True,
            ),
        ),
    ]
