# Generated by Django 5.2.13 on 2026-08-04 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import lumina.vendors.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=140, unique=True)),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("hardware", "Hardware"),
                            ("software", "Software"),
                            ("both", "Hardware and software"),
                        ],
                        db_index=True,
                        default="hardware",
                        help_text="Which catalog this vendor appears in. Memberships, aliases and verification are shared regardless.",
                        max_length=16,
                    ),
                ),
                ("homepage", models.URLField(blank=True)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=lumina.vendors.models._vendor_logo_path,
                    ),
                ),
                (
                    "verified",
                    models.BooleanField(
                        default=False,
                        help_text="When true, submissions on behalf of this vendor are eligible for vendor-validated trust level. Toggled by AlmaLinux admins after verifying the vendor relationship.",
                    ),
                ),
                (
                    "published",
                    models.BooleanField(
                        default=True,
                        help_text="False for vendors created inline on a hardware submission still awaiting reviewer approval. The public catalog only shows published vendors; admin sees both.",
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="VendorAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="vendors.vendor",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "vendor aliases",
            },
        ),
        migrations.CreateModel(
            name="VendorProposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("create", "Create"), ("update", "Update")],
                        max_length=8,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=120)),
                ("homepage", models.URLField(blank=True)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("description", models.TextField(blank=True)),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("hardware", "Hardware"),
                            ("software", "Software"),
                            ("both", "Hardware and software"),
                        ],
                        default="hardware",
                        max_length=16,
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=lumina.vendors.models._vendor_proposal_logo_path,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("needs-changes", "Needs changes"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("reviewer_notes", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "proposed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vendor_proposals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_vendor_proposals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proposals",
                        to="vendors.vendor",
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="VendorClaim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "work_email",
                    models.EmailField(
                        help_text="An address at the vendor's own domain carries the most weight.",
                        max_length=254,
                    ),
                ),
                ("role_at_vendor", models.CharField(max_length=120)),
                ("note", models.TextField(blank=True)),
                (
                    "evidence",
                    models.FileField(
                        blank=True,
                        upload_to=lumina.vendors.models._vendor_claim_evidence_path,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("needs-changes", "Needs changes"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("reviewer_notes", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vendor_claims",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_vendor_claims",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claims",
                        to="vendors.vendor",
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("status__in", ("pending", "needs-changes"))
                        ),
                        fields=("vendor", "requester"),
                        name="one_open_claim_per_vendor_and_requester",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="VendorMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("member", "Member"),
                            ("submitter", "Submitter"),
                            ("owner", "Owner"),
                        ],
                        default="member",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendor_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="vendors.vendor",
                    ),
                ),
            ],
            options={
                "ordering": ["vendor__name"],
                "unique_together": {("user", "vendor")},
            },
        ),
    ]
