# Generated by Django 5.2.13 on 2026-09-25 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0002_pci_ids_vendor_aliases"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendor",
            name="homepage",
            field=models.URLField(blank=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name="vendorproposal",
            name="homepage",
            field=models.URLField(blank=True, max_length=2048),
        ),
    ]
