# Generated by Django 5.2.13 on 2026-09-18 16:26

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import lumina.core.review


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("results", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SurveySegment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
                ("slug", models.SlugField(max_length=80, unique=True)),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Shown on the statistics page, so say what the cohort is.",
                        max_length=300,
                    ),
                ),
                (
                    "criteria",
                    models.JSONField(
                        default=list,
                        help_text='Clauses, all of which must match: [{"field": "arch", "op": "eq", "value": "aarch64"}]. Operators: eq, ne, in, contains, gt, gte, lt, lte, isnull, not_blank.',
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Disabled segments stay in the rollup but are not offered on the page.",
                    ),
                ),
                (
                    "position",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Order in the picker; ties fall back to the name.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["position", "name"],
            },
        ),
        migrations.CreateModel(
            name="SurveyStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("segment", models.CharField(blank=True, db_index=True, max_length=80)),
                (
                    "period",
                    models.CharField(
                        db_index=True, help_text='"2026" or "2026-09".', max_length=16
                    ),
                ),
                (
                    "dimension",
                    models.CharField(
                        db_index=True,
                        help_text="cpu_family, gpu_vendor, ...",
                        max_length=40,
                    ),
                ),
                ("bucket", models.CharField(max_length=200)),
                ("count", models.PositiveIntegerField(default=0)),
                ("dedup_key", models.CharField(max_length=16)),
                ("tier_scope", models.CharField(max_length=16)),
                ("computed_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["dimension", "-count"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "segment",
                            "period",
                            "dimension",
                            "bucket",
                            "dedup_key",
                            "tier_scope",
                        ),
                        name="survey_stat_unique_bucket",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SurveyTokenGrant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("granted_at", models.DateTimeField(auto_now_add=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "max_ttl_seconds",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Longest token this account may mint. Null uses LUMINA_SURVEY_MAX_TOKEN_TTL_SECONDS.",
                        null=True,
                    ),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="survey_token_grant",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SurveySubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("received_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("survey", "Survey run"),
                            ("cert-run", "Cert-run fork"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                (
                    "trust_tier",
                    models.CharField(
                        choices=[("verified", "Verified"), ("community", "Community")],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("source_ip_hash", models.CharField(blank=True, max_length=64)),
                ("system_uuid", models.CharField(blank=True, max_length=64)),
                ("system_serial", models.CharField(blank=True, max_length=128)),
                ("board_serial", models.CharField(blank=True, max_length=128)),
                ("machine_id", models.CharField(blank=True, max_length=64)),
                (
                    "identity_hash",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                (
                    "identity_source",
                    models.CharField(
                        blank=True,
                        help_text="Which raw signal keyed identity_hash: smbios_uuid | board_serial | machine_id.",
                        max_length=16,
                    ),
                ),
                ("virtual", models.BooleanField(db_index=True, default=False)),
                ("virt_kind", models.CharField(blank=True, max_length=32)),
                ("inventory", models.JSONField(default=dict)),
                (
                    "cpu_model",
                    models.CharField(blank=True, db_index=True, max_length=200),
                ),
                (
                    "cpu_family",
                    models.CharField(blank=True, db_index=True, max_length=120),
                ),
                (
                    "cpu_vendor",
                    models.CharField(blank=True, db_index=True, max_length=80),
                ),
                (
                    "cpu_sockets",
                    models.PositiveSmallIntegerField(
                        blank=True, db_index=True, null=True
                    ),
                ),
                ("cpu_cores", models.PositiveIntegerField(blank=True, null=True)),
                ("cpu_threads", models.PositiveIntegerField(blank=True, null=True)),
                ("memory_bytes", models.PositiveBigIntegerField(blank=True, null=True)),
                (
                    "memory_type",
                    models.CharField(blank=True, db_index=True, max_length=32),
                ),
                (
                    "gpu_vendor",
                    models.CharField(blank=True, db_index=True, max_length=80),
                ),
                (
                    "gpu_model",
                    models.CharField(blank=True, db_index=True, max_length=200),
                ),
                (
                    "board_vendor",
                    models.CharField(blank=True, db_index=True, max_length=120),
                ),
                (
                    "board_model",
                    models.CharField(blank=True, db_index=True, max_length=200),
                ),
                ("arch", models.CharField(blank=True, db_index=True, max_length=32)),
                (
                    "x86_64_level",
                    models.CharField(blank=True, db_index=True, max_length=8),
                ),
                ("kernel", models.CharField(blank=True, max_length=120)),
                (
                    "os_major",
                    models.PositiveSmallIntegerField(
                        blank=True, db_index=True, null=True
                    ),
                ),
                (
                    "os_minor",
                    models.PositiveSmallIntegerField(
                        blank=True, db_index=True, null=True
                    ),
                ),
                (
                    "review_state",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("accepted", "Accepted"),
                            ("dismissed", "Dismissed"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=12,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_survey_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="survey_forks",
                        to="results.testrun",
                    ),
                ),
                (
                    "submitter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="survey_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "token",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="accounts.apitoken",
                    ),
                ),
            ],
            options={
                "ordering": ["-received_at"],
                "indexes": [
                    models.Index(
                        fields=["identity_hash", "received_at"],
                        name="survey_surv_identit_37ec43_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SurveyTokenRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "justification",
                    models.TextField(
                        help_text="Why this account needs long-lived survey tokens (fleet size, automation, ...)."
                    ),
                ),
                (
                    "requested_ttl_seconds",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("needs-changes", "Needs changes"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("reviewer_notes", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="survey_token_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_survey_token_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("status__in", ["pending", "needs-changes"])
                        ),
                        fields=("requester",),
                        name="survey_token_request_one_open_per_user",
                    )
                ],
            },
            bases=(lumina.core.review.ReviewWorkflow, models.Model),
        ),
    ]
