# Generated by Django 5.2.13 on 2026-09-04 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0002_surveysubmission_reviewed_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SurveySegment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
                ("slug", models.SlugField(max_length=80, unique=True)),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Shown on the statistics page, so say what the cohort is.",
                        max_length=300,
                    ),
                ),
                (
                    "criteria",
                    models.JSONField(
                        default=list,
                        help_text='Clauses, all of which must match: [{"field": "arch", "op": "eq", "value": "aarch64"}]. Operators: eq, ne, in, contains, gt, gte, lt, lte, isnull, not_blank.',
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Disabled segments stay in the rollup but are not offered on the page.",
                    ),
                ),
                (
                    "position",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Order in the picker; ties fall back to the name.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["position", "name"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="surveystat",
            name="survey_stat_unique_bucket",
        ),
        migrations.AddField(
            model_name="surveystat",
            name="segment",
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
        migrations.AddConstraint(
            model_name="surveystat",
            constraint=models.UniqueConstraint(
                fields=(
                    "segment",
                    "period",
                    "dimension",
                    "bucket",
                    "dedup_key",
                    "tier_scope",
                ),
                name="survey_stat_unique_bucket",
            ),
        ),
    ]
