# Generated by Django 5.2.13 on 2026-09-11 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("results", "0014_testrun_publish_anonymously"),
        ("survey", "0003_surveysegment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="surveysubmission",
            name="source_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="survey_forks",
                to="results.testrun",
            ),
        ),
    ]
