# Generated by Django 5.2.13 on 2026-08-04 18:55

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import lumina.software.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("releases", "0001_initial"),
        ("taxonomy", "0001_initial"),
        ("vendors", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Software",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                ("description", models.TextField(blank=True)),
                ("homepage_url", models.URLField(blank=True)),
                ("documentation_url", models.URLField(blank=True)),
                ("support_url", models.URLField(blank=True)),
                ("published", models.BooleanField(default=False)),
                (
                    "validation_level",
                    models.CharField(
                        choices=[
                            ("community", "Community-validated"),
                            ("vendor", "Vendor-validated"),
                            ("almalinux", "AlmaLinux-validated"),
                        ],
                        db_index=True,
                        default="community",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner_vendor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Vendor responsible for keeping this entry accurate; drives edit rights. Null means community-submitted and nobody has claimed it.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_software",
                        to="vendors.vendor",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        help_text="Who publishes it.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="vendors.vendor",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "software",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SoftwareCompatibility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "validation_level",
                    models.CharField(
                        choices=[
                            ("community", "Community-validated"),
                            ("vendor", "Vendor-validated"),
                            ("almalinux", "AlmaLinux-validated"),
                        ],
                        default="community",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Awaiting review"),
                            ("approved", "Approved"),
                        ],
                        default="approved",
                        max_length=16,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "proposed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set only when a community member cited this major.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="proposed_software_majors",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "release",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="software_compatibility",
                        to="releases.almalinuxrelease",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_software_majors",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "software",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compatibility",
                        to="software.software",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "software compatibility",
                "ordering": ["-release__major"],
            },
        ),
        migrations.CreateModel(
            name="SoftwareCertification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("vendor", "Vendor-validated"),
                            ("almalinux", "AlmaLinux-validated"),
                        ],
                        max_length=16,
                    ),
                ),
                ("certified_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "certified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="software_certifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "compatibility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certifications",
                        to="software.softwarecompatibility",
                    ),
                ),
            ],
            options={
                "ordering": ["level"],
            },
        ),
        migrations.CreateModel(
            name="SoftwareAttestation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="software_attestations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "compatibility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attestations",
                        to="software.softwarecompatibility",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SoftwareEditProposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                ("homepage_url", models.URLField(blank=True)),
                ("documentation_url", models.URLField(blank=True)),
                ("support_url", models.URLField(blank=True)),
                ("submitter_notes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("needs-changes", "Needs changes"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("reviewer_notes", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "proposed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="software_edit_proposals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_software_edits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "software",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="edit_proposals",
                        to="software.software",
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="SoftwareSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "claimed_validation_level",
                    models.CharField(
                        choices=[
                            ("community", "Community-validated"),
                            ("vendor", "Vendor-validated"),
                            ("almalinux", "AlmaLinux-validated"),
                        ],
                        default="community",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("needs-changes", "Needs changes"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("reviewer_notes", models.TextField(blank=True)),
                ("submitter_notes", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "on_behalf_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="software_submissions",
                        to="vendors.vendor",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_software_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "software",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="software.software",
                    ),
                ),
                (
                    "submitter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="software_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="SoftwareEvidenceAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=lumina.software.models._evidence_upload_to
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=300)),
                ("sha256", models.CharField(blank=True, max_length=64)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="software.softwaresubmission",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SoftwareCategoryValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "software",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_values",
                        to="software.software",
                    ),
                ),
                (
                    "value",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="software_bindings",
                        to="taxonomy.categoryvalue",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("software", "value"), name="unique_software_value"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="softwarecompatibility",
            constraint=models.UniqueConstraint(
                fields=("software", "release"), name="one_row_per_software_and_major"
            ),
        ),
        migrations.AddConstraint(
            model_name="softwarecertification",
            constraint=models.UniqueConstraint(
                fields=("compatibility", "level"),
                name="one_certification_per_major_and_validator",
            ),
        ),
        migrations.AddConstraint(
            model_name="softwareattestation",
            constraint=models.UniqueConstraint(
                fields=("compatibility", "user"),
                name="one_attestation_per_user_and_major",
            ),
        ),
    ]
