# Generated by Django 5.2.13 on 2026-09-21 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("releases", "0002_seed_releases"),
        ("software", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="softwaresubmission",
            name="cited_releases",
            field=models.ManyToManyField(
                blank=True,
                related_name="software_submissions",
                to="releases.almalinuxrelease",
            ),
        ),
    ]
