# Generated by Django 5.2.13 on 2026-09-25 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("software", "0002_submission_cited_releases"),
    ]

    operations = [
        migrations.AlterField(
            model_name="software",
            name="documentation_url",
            field=models.URLField(blank=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name="software",
            name="homepage_url",
            field=models.URLField(blank=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name="software",
            name="support_url",
            field=models.URLField(blank=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name="softwareeditproposal",
            name="documentation_url",
            field=models.URLField(blank=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name="softwareeditproposal",
            name="homepage_url",
            field=models.URLField(blank=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name="softwareeditproposal",
            name="support_url",
            field=models.URLField(blank=True, max_length=2048),
        ),
    ]
