# Generated by Django 5.2.13 on 2026-09-07 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_accountsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountsettings",
            name="chat_dm",
            field=models.BooleanField(
                default=False,
                help_text="Send a Mattermost direct message when something needs this user's attention.",
            ),
        ),
        migrations.AddField(
            model_name="accountsettings",
            name="chat_handle",
            field=models.CharField(
                blank=True,
                help_text="Mattermost username, without the @. Blank means the same as the AlmaLinux username.",
                max_length=150,
            ),
        ),
        migrations.AddField(
            model_name="accountsettings",
            name="email_notifications",
            field=models.BooleanField(
                default=True,
                help_text="Send email when something needs this user's attention.",
            ),
        ),
    ]
