# Generated by Django 5.2.13 on 2026-09-15 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0003_accountsettings_chat_dm_accountsettings_chat_handle_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accountsettings",
            name="chat_handle",
        ),
    ]
