# Generated by Django 5.2.13 on 2026-09-15 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_remove_accountsettings_chat_handle"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationDefaults",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_notifications",
                    models.BooleanField(
                        default=True,
                        help_text="New accounts are emailed when something needs their attention.",
                    ),
                ),
                (
                    "chat_dm",
                    models.BooleanField(
                        default=True,
                        help_text="New accounts are sent a chat direct message as well.",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "notification defaults",
                "verbose_name_plural": "notification defaults",
            },
        ),
        migrations.AlterField(
            model_name="accountsettings",
            name="chat_dm",
            field=models.BooleanField(
                default=True,
                help_text="Send a Mattermost direct message when something needs this user's attention.",
            ),
        ),
    ]
