# Generated by Django 5.2.13 on 2026-09-18 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_key",
                    models.CharField(
                        help_text="The event this policy covers. See the notification event registry.",
                        max_length=60,
                        unique=True,
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "notification policies",
                "ordering": ["event_key"],
            },
        ),
        migrations.CreateModel(
            name="NotificationEndpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="A label for this endpoint.", max_length=120
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="Where the POST is sent. Blank for email, which has no URL.",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("mattermost", "Mattermost incoming webhook"),
                            ("generic", "Generic (HMAC-signed event JSON)"),
                        ],
                        default="generic",
                        help_text="Generic posts the signed event JSON. Mattermost posts a chat message to an incoming-webhook URL - no signature, the unguessable URL is the secret.",
                        max_length=16,
                    ),
                ),
                (
                    "secret",
                    models.CharField(
                        blank=True,
                        help_text="Generic only: the shared secret the receiver verifies the X-Lumina-Signature HMAC against. Generated on first save if left blank; unused for Mattermost.",
                        max_length=64,
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_delivery_at", models.DateTimeField(blank=True, null=True)),
                ("last_status", models.CharField(blank=True, max_length=40)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="NotificationEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_key", models.CharField(db_index=True, max_length=60)),
                ("target_id", models.PositiveBigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "processed_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("webhook", "Webhook"),
                            ("chat", "Chat direct message"),
                        ],
                        max_length=10,
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("handle", models.CharField(blank=True, max_length=150)),
                ("audience", models.CharField(blank=True, max_length=16)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                (
                    "next_attempt_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("last_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "endpoint",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="notifications.notificationendpoint",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="notifications.notificationevent",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "notification deliveries",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="PolicyDestination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            (
                                "person",
                                "To each person in the audience (an email, or a chat direct message)",
                            ),
                            (
                                "room",
                                "To a shared place (a chat channel, or a webhook consumer)",
                            ),
                        ],
                        default="person",
                        max_length=10,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        blank=True,
                        help_text="Chat rooms only: the channel to post in, overriding the one the incoming webhook is locked to. Blank uses the webhook's own channel.",
                        max_length=120,
                    ),
                ),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            (
                                "reviewers",
                                "Reviewers (the reviewer groups, plus LUMINA_REVIEW_NOTIFY_EMAILS)",
                            ),
                            ("submitter", "The person the object belongs to"),
                            (
                                "vendor_members",
                                "Submit-role members of the owning vendor",
                            ),
                        ],
                        default="reviewers",
                        help_text="Who this is for. Addressed at a person it decides who hears; addressed at a room it decides where the link points, since a reviewer message should open the queue and a personal one the object itself.",
                        max_length=16,
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                (
                    "endpoint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="destinations",
                        to="notifications.notificationendpoint",
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="destinations",
                        to="notifications.notificationpolicy",
                    ),
                ),
            ],
            options={
                "ordering": ["endpoint", "kind", "channel"],
            },
        ),
        migrations.AddIndex(
            model_name="notificationevent",
            index=models.Index(
                fields=["target_content_type", "target_id"],
                name="notificatio_target__d87e35_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="notificationdelivery",
            constraint=models.UniqueConstraint(
                fields=("event", "channel", "email", "endpoint", "handle"),
                name="notification_delivery_unique_destination",
            ),
        ),
        migrations.AddConstraint(
            model_name="policydestination",
            constraint=models.UniqueConstraint(
                fields=("policy", "endpoint", "kind", "channel", "audience"),
                name="notification_destination_unique",
            ),
        ),
    ]
