# Generated by Django 5.2.13 on 2026-08-31 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notificationdelivery",
            options={
                "ordering": ["created_at"],
                "verbose_name_plural": "notification deliveries",
            },
        ),
    ]
