# Generated by Django 5.2.13 on 2026-08-31 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_alter_notificationdelivery_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="webhookendpoint",
            name="kind",
            field=models.CharField(
                choices=[
                    ("generic", "Generic (HMAC-signed event JSON)"),
                    ("mattermost", "Mattermost incoming webhook"),
                ],
                default="generic",
                help_text="Generic posts the signed event JSON. Mattermost posts a chat message to an incoming-webhook URL - no signature, the unguessable URL is the secret.",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="webhookendpoint",
            name="secret",
            field=models.CharField(
                blank=True,
                help_text="Generic only: the shared secret the receiver verifies the X-Lumina-Signature HMAC against. Generated on first save if left blank; unused for Mattermost.",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="webhookendpoint",
            name="url",
            field=models.URLField(help_text="Where the POST is sent."),
        ),
    ]
