# Generated by Django 5.2.13 on 2026-09-25 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_seed_email_policies"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationendpoint",
            name="url",
            field=models.URLField(
                blank=True,
                help_text="Where the POST is sent. Blank for email, which has no URL.",
                max_length=2048,
            ),
        ),
    ]
