# Generated by Django 5.2.13 on 2026-09-07 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "notifications",
            "0003_webhookendpoint_kind_alter_webhookendpoint_secret_and_more",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="notificationdelivery",
            name="notification_delivery_unique_destination",
        ),
        migrations.AddField(
            model_name="notificationdelivery",
            name="handle",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="webhookendpoint",
            name="direct_messages",
            field=models.BooleanField(
                default=False,
                help_text="Use this endpoint to send direct messages to individual users. Mattermost only, and only where the incoming webhook is NOT locked to a single channel, since a direct message overrides the channel.",
            ),
        ),
        migrations.AlterField(
            model_name="notificationdelivery",
            name="channel",
            field=models.CharField(
                choices=[
                    ("email", "Email"),
                    ("webhook", "Webhook"),
                    ("chat", "Chat direct message"),
                ],
                max_length=10,
            ),
        ),
        migrations.AddConstraint(
            model_name="notificationdelivery",
            constraint=models.UniqueConstraint(
                fields=("event", "channel", "email", "endpoint", "handle"),
                name="notification_delivery_unique_destination",
            ),
        ),
    ]
