# Generated by Django 5.2.13, split by hand: the data migration between this and 0007 reads the
# endpoint fields 0007 removes, so the schema change cannot happen in one step.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "notifications",
            "0004_remove_notificationdelivery_notification_delivery_unique_destination_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationdelivery",
            name="audience",
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.CreateModel(
            name="NotificationRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_key",
                    models.CharField(
                        db_index=True,
                        help_text='The event this rule covers, or "*" for every event. See the notification event registry for the list.',
                        max_length=60,
                    ),
                ),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            (
                                "reviewers",
                                "Reviewers (the reviewer groups, plus LUMINA_REVIEW_NOTIFY_EMAILS)",
                            ),
                            ("submitter", "The person the object belongs to"),
                            (
                                "vendor_members",
                                "Submit-role members of the owning vendor",
                            ),
                        ],
                        help_text="Who the notification is addressed at. For email and direct messages this decides the recipients; for a post it decides where the link points, since a reviewer message should open the queue and a personal one the object itself.",
                        max_length=16,
                    ),
                ),
                (
                    "transport",
                    models.CharField(
                        choices=[
                            ("email", "Email, one per person"),
                            ("chat_dm", "Chat direct message, one per person"),
                            (
                                "post",
                                "Post to the endpoint: a chat channel, or a generic webhook",
                            ),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        blank=True,
                        help_text="Posts only: the Mattermost channel to post in, overriding the one the incoming webhook is locked to. Blank uses the webhook's own channel.",
                        max_length=120,
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                (
                    "endpoint",
                    models.ForeignKey(
                        blank=True,
                        help_text="Required for direct messages and posts. Leave blank for email.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routes",
                        to="notifications.webhookendpoint",
                    ),
                ),
            ],
            options={
                "ordering": ["event_key", "audience", "transport"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "event_key",
                            "audience",
                            "transport",
                            "endpoint",
                            "channel",
                        ),
                        name="notification_route_unique_rule",
                    )
                ],
            },
        ),
    ]
