# Generated by Django 5.2.13 on 2026-09-15 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0007_endpoint_stops_subscribing"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_key",
                    models.CharField(
                        help_text="The event this policy covers. See the notification event registry.",
                        max_length=60,
                        unique=True,
                    ),
                ),
                (
                    "email_audiences",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Who is emailed about this event. Empty means nobody.",
                    ),
                ),
                (
                    "dm_audiences",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Who is sent a chat direct message about this event. Empty means nobody.",
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                (
                    "dm_endpoint",
                    models.ForeignKey(
                        blank=True,
                        help_text="The Mattermost endpoint direct messages go through. Required if anybody is to be messaged; its incoming webhook must not be locked to a single channel, since a direct message overrides the channel.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dm_policies",
                        to="notifications.webhookendpoint",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "notification policies",
                "ordering": ["event_key"],
            },
        ),
        migrations.CreateModel(
            name="PolicyPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        blank=True,
                        help_text="The Mattermost channel to post in, overriding the one the incoming webhook is locked to. Blank uses the webhook's own channel. Mattermost only.",
                        max_length=120,
                    ),
                ),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            (
                                "reviewers",
                                "Reviewers (the reviewer groups, plus LUMINA_REVIEW_NOTIFY_EMAILS)",
                            ),
                            ("submitter", "The person the object belongs to"),
                            (
                                "vendor_members",
                                "Submit-role members of the owning vendor",
                            ),
                        ],
                        default="reviewers",
                        help_text="Who the post is addressed at. It decides where the link points: a reviewer message opens the queue, a personal one the object itself.",
                        max_length=16,
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                (
                    "endpoint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="policy_posts",
                        to="notifications.webhookendpoint",
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="notifications.notificationpolicy",
                    ),
                ),
            ],
            options={
                "ordering": ["endpoint", "channel"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("policy", "endpoint", "channel"),
                        name="notification_post_unique_room",
                    )
                ],
            },
        ),
    ]
