# Generated by Django 5.2.13 on 2026-09-15 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0009_routes_become_policies"),
    ]

    operations = [
        migrations.DeleteModel(
            name="NotificationRoute",
        ),
    ]
