# Generated by Django 5.2.13 on 2026-09-15 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0012_dm_endpoints_become_destinations"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notificationpolicy",
            name="dm_audiences",
        ),
        migrations.RemoveField(
            model_name="notificationpolicy",
            name="dm_endpoint",
        ),
    ]
