# Generated by Django 5.2.13 on 2026-09-15 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0015_email_becomes_a_destination"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notificationpolicy",
            name="email_audiences",
        ),
        migrations.AlterField(
            model_name="policydestination",
            name="audience",
            field=models.CharField(
                choices=[
                    (
                        "reviewers",
                        "Reviewers (the reviewer groups, plus LUMINA_REVIEW_NOTIFY_EMAILS)",
                    ),
                    ("submitter", "The person the object belongs to"),
                    ("vendor_members", "Submit-role members of the owning vendor"),
                ],
                default="reviewers",
                help_text="Who this is for. Addressed at a person it decides who hears; addressed at a room it decides where the link points, since a reviewer message should open the queue and a personal one the object itself.",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="policydestination",
            name="channel",
            field=models.CharField(
                blank=True,
                help_text="Chat rooms only: the channel to post in, overriding the one the incoming webhook is locked to. Blank uses the webhook's own channel.",
                max_length=120,
            ),
        ),
    ]
