# Generated by Django 5.2.13 on 2026-08-04 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                (
                    "applies_to",
                    models.CharField(
                        choices=[
                            ("system", "Systems only"),
                            ("component", "Components only"),
                            ("both", "Systems and Components"),
                            ("software", "Software only"),
                        ],
                        default="both",
                        max_length=16,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "derived_from_runs",
                    models.BooleanField(
                        default=False,
                        help_text="Set from an approved validation run's own report. Hidden from the submit forms, because the machine is the authority on it.",
                    ),
                ),
                (
                    "collapsed_limit",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="Number of values shown before the 'Expand + search' control appears in the filter panel.",
                    ),
                ),
                (
                    "picker_widget",
                    models.CharField(
                        choices=[
                            ("dropdown", "Dropdown"),
                            ("checkboxes", "Checkboxes"),
                            ("multiselect", "Multiselect"),
                        ],
                        default="checkboxes",
                        help_text="How this category is rendered on the submission form. Use 'dropdown' for axes where a listing has at most one value (e.g. Architecture). 'multiselect' suits long lists; 'checkboxes' suits short ones where every option should be visible at a glance.",
                        max_length=16,
                    ),
                ),
                (
                    "allow_suggestions",
                    models.BooleanField(
                        default=True,
                        help_text="If True, submitters may propose a new value for this category via an inline 'Propose new …' input. Disable for curated axes (e.g. AlmaLinux versions, which only the Foundation can release).",
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Categories",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="CategoryValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=120)),
                ("slug", models.SlugField(blank=True, max_length=140)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="approved",
                        max_length=16,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_taxonomy_values",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="taxonomy.category",
                    ),
                ),
                (
                    "proposed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="proposed_taxonomy_values",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["category__display_order", "value"],
                "unique_together": {("category", "value")},
            },
        ),
    ]
