# Generated by Django 5.2.13 on 2026-09-18 16:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DisplayDefaults",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rows_per_page",
                    models.PositiveIntegerField(
                        default=20,
                        help_text="Rows per page on the dashboard and the review archive. Between 1 and 500.",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(500),
                        ],
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "display defaults",
                "verbose_name_plural": "display defaults",
            },
        ),
    ]
